recipe/urls.py
from django.urls import path, include

from .views import (
    RecipeListView,
    RecipeDetailView,
    RecipeCreateView,
    RecipeUpdateView,
    RecipeDeleteView,
    RecipeCategoryList,
    HomeView
    )

app_name = "recipe"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('list/', RecipeListView.as_view(), name='list'),
    path('<int:pk>/detail/', RecipeDetailView.as_view(), name='detail'),
    path("create/", RecipeCreateView.as_view(), name='create'),
    path("category/<slug:cat>/", RecipeCategoryList.as_view(), name='category'),
    
    path("<int:pk>/update/", RecipeUpdateView.as_view(), name='update'),
    path("<int:pk>/delete/", RecipeDeleteView.as_view(), name='delete'),
]

recipeBox/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("recipe.urls")),
    path("review/", include("review.urls")),
    path("accounts/", include("accounts.urls")),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/Base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock title %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Base.css' %}">
</head>
<body>

<nav class="navbar">
        <ul class="nav-list">
            <li class="nav-item"><a href="{% url 'recipe:home' %}">Home</a></li>

            {% if user.is_authenticated %}
                <li class="nav-item"><a href="{% url 'profile' user.username %}">profile</a></li>

                <li class="nav-item"><a href="{% url 'account_logout' %}">Logout</a></li>


            {% else %}
                <li class="nav-item"><a href="{% url 'account_login' %}">Login</a></li>
                <li class="nav-item"><a href="{% url 'account_signup' %}">Sign Up</a></li>
            {% endif %}
                <li class="nav-item"><a href="{% url 'recipe:list' %}">Lstest Posts</a></li>

        </ul>
    </nav>

    {% block content %}{% endblock content %}

    <div class="pagination">
        <span class="step-links">
            {% if page_obj %}
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current-page">page: {{ page_obj.number }}</span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
                            
            {% else %}
                <span class="current-page">page: 1</span>
            {% endif %}
        </span>
    </div>

    <script src="" async defer></script>
</body>
</html>