recipe/urls.py
from django.urls import path, include

from .views import (
    RecipeListView,
    RecipeDetailView,
    RecipeCreateView,
    RecipeUpdateView,
    RecipeDeleteView,
    RecipeCategoryList,
    HomeView
    )

app_name = "recipe"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('list/', RecipeListView.as_view(), name='list'),
    path('<int:pk>/detail/', RecipeDetailView.as_view(), name='detail'),
    path("create/", RecipeCreateView.as_view(), name='create'),
    path("category/<slug:cat>/", RecipeCategoryList.as_view(), name='category'),
    
    path("<int:pk>/update/", RecipeUpdateView.as_view(), name='update'),
    path("<int:pk>/delete/", RecipeDeleteView.as_view(), name='delete'),
]

recipeBox/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("recipe.urls")),
    path("review/", include("review.urls")),
    path("accounts/", include("accounts.urls")),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

review/urls.py
from django.urls import path

from .views import (
    RecipeAddComment,
    RecipeAddLike,
    RecipeAddToFavorite,
    )

app_name = "review"

urlpatterns = [
    path("<int:pk>/comment/", RecipeAddComment.as_view(), name='comment'),
    path("<int:pk>/like/", RecipeAddLike.as_view(), name='like'),
    path("<int:pk>/fav/", RecipeAddToFavorite.as_view(), name='favorite'),
]

recipe/models.py
from django.db import models
from django.contrib.auth import get_user_model

from django.utils.translation import gettext_lazy as _

User = get_user_model()

    
class Category(models.Model):
    name = models.CharField(max_length=200, verbose_name=_("Name"))
    parent = models.ForeignKey('self', related_name="children", on_delete=models.CASCADE, null=True, blank=True)
    
    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')

class Recipe(models.Model):
    created_time = models.DateTimeField(auto_now_add=True, verbose_name=_("Created time"))
    modified_time = models.DateTimeField(verbose_name=_("Modified time"), auto_now=True)
    title = models.CharField(max_length=150, verbose_name=_("Title"), unique=True)
    description = models.TextField(blank=True, null=True, verbose_name=_("Description"))
    instructions = models.TextField(verbose_name=_("Instructions"))
    time_to_cook = models.DurationField(verbose_name=_("time to cook"))
    image = models.ImageField(upload_to="images/", verbose_name=_("Image"), null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="recipe", verbose_name=_("User"))
    # like = models.PositiveBigIntegerField(default=0, )
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name="categories", verbose_name=_("Category"))
    
    def __str__(self):
        return f"{self.title} - {self.created_time}"
    

recipe/forms.py
from django import forms

from .models import Recipe


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ("title", "description", "instructions", "time_to_cook", "image", "category")

recipe/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import DetailView, UpdateView, DeleteView, ListView
from django.db.models import Count, Q
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.cache import cache_page
from django_filters import FilterSet
from django_filters.views import FilterView

from django.utils import timezone
from datetime import timedelta

from .models import Recipe, Category
from .forms import RecipeForm
from review.forms import RecipeAddLikeForm, RecipeAddCommentForm

class HomeFilter(FilterSet):
    class Meta:
        model = Recipe
        fields = {"title": ["contains"], "category": ["exact"]}
                
"""
class RecipeListView(View):
    template_name = "recipes/recipe_list.html"
    def get(self, request, *args, **kwargs):  # commenting this because im going to use filter view
        qs = Recipe.objects.annotate(like_count=Count("likes")).prefetch_related("likes").all()
        context = {"recipes": qs}
        return render(request, self.template_name, context)
"""  

class RecipeListView(FilterView):
    filterset_class = HomeFilter
    paginate_by = 10
    template_name = "recipes/recipe_list.html"
    context_object_name = "recipes"
    model = Recipe
    
    @method_decorator(cache_page(60 * 5))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
    
    def get_queryset(self):        
        qs = super().get_queryset()
        return qs.annotate(like_count=Count("likes")).prefetch_related("likes").all()
    
    
class RecipeDetailView(DetailView):
    template_name = "recipes/recipe_detail.html"
    context_object_name = "recipe"

    
    def get_queryset(self):
        pk = self.kwargs["pk"]
        return Recipe.objects.annotate(like_count=Count("likes")).prefetch_related("likes", "comments").filter(pk=pk)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        recipe = context['recipe']
        context["comments"] = recipe.comments.all()
        context["comment_form"] = RecipeAddCommentForm()
        context["like_form"] = RecipeAddLikeForm()
        return context
            
"""           
class RecipeCreateView(LoginRequiredMixin, FormView):
    form_class = RecipeForm
    
    template_name = "recipes/recipe_create.html"
    success_url = "/"
    
    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.save()
        return HttpResponseRedirect(self.success_url)
"""       

class RecipeCreateView(View):
    template_name = "recipes/recipe_create.html"
    
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
    
    def get(self, request, *args, **kwargs):
        form = RecipeForm
        context = {"form": form}
        return render(request, self.template_name,context)
    def post(self, request, *args, **kwargs):
        form = RecipeForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            obj.save()
            return HttpResponseRedirect("/")
        raise Http404
    
class RecipeUpdateView(UpdateView):
    template_name = "recipes/recipe_update.html"
    form_class = RecipeForm
    context_object_name = "recipe"
    success_url = "/"
    
    def get_queryset(self):
        return Recipe.objects.filter(pk=self.kwargs['pk'])
    
    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if request.user == obj.user:
            return super().dispatch(request, *args, **kwargs)
        else:
            raise Http404
    
    
class RecipeDeleteView(DeleteView):
    template_name = "recipes/recipe_confirm_delete.html"
    model = Recipe
    success_url = "/"
    
    def dispatch(self, request, *args, **kwargs):
        self.obj = self.get_object()
        if request.user == self.obj.user: # if user in owner
            return super().dispatch(request, *args, **kwargs)
        else:
            raise Http404
        
    def get_queryset(self):
        return Recipe.objects.filter(pk=self.kwargs['pk'])
    
    def delete(self, request, *args, **kwargs):
        if request.method == 'POST':
            self.obj.delete()
            return HttpResponseRedirect(self.success_url)


class RecipeCategoryList(ListView):
    template_name = "recipes/category_list.html"
    model = Category
    context_object_name = "recipes"
    paginate_by = 10
    
    def get_queryset(self):
        category = self.kwargs.get("cat")
        print(category)
        return Recipe.objects.filter(category__name=category)
    

class HomeView(View):    
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            user = request.user
            following = user.following.all()
            two_weeks = timezone.now() - timedelta(weeks=2)
            recipe = Recipe.objects.annotate(like_count=Count("likes")).prefetch_related("likes").filter(Q(user__in=following)&Q(created_time__gte=two_weeks))
            context = {"recipes": recipe}
            return render(request, "recipes/Home.html", context)
        else:
            return HttpResponseRedirect(reverse_lazy("recipe:list"))

templates/recipes/Home.html
{% extends 'Base.html' %}

{% block title %}
Home feed 
{% endblock title %}

{% block content %}
{% if recipes %}

<ul>
    {% for recipe in recipes %}
    <li><a href="{% url 'recipe:detail' recipe.pk %}" >{{recipe.title}}</a> by user {{recipe.user}} likes: {{recipe.like_count}} </li>
    {% if recipe.image %}
        <img src="{{recipe.image.url}}" alt="{{recipe.title}}" width="200" height="150">
        {% endif %}
    {% endfor %}
</ul>

{% else %}
<h1> owwww Home feed empty :( </h1>
{% endif %}
{% endblock content %}

templates/recipes/category_list.html
{% extends 'Base.html' %}
{% block title %}
Category list-view
{% endblock title %}

{% block content %}
<ul>
    {% for recipe in recipes %}
        <li><a href="{% url 'recipe:detail' recipe.pk %}" >{{recipe.title}}</a> by user {{recipe.user}} likes: {{recipe.like_count}} </li>
        {% if recipe.image %}
        <img src="{{recipe.image.url}}" alt="{{recipe.title}}" width="200" height="150">
        {% endif %}
    {% endfor %}
</ul>
{% endblock content %}

templates/recipes/recipe_confirm_delete.html
{% extends 'Base.html' %}
{% block title %}
Recipe deleted 
{% endblock title %}

{% block content %}
<h1>deleted the recipe</h1>
<form method="post">
    {% csrf_token %}

    <input type="submit" value="delete">
</form>
<a href="{% url 'recipe:list' %}">Return to home</a>
{% endblock content %}

templates/recipes/recipe_create.html
{% extends 'Base.html' %}

{% block title %}Create a recipe{% endblock title %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Create" />
</form> 
{% endblock content %}

templates/recipes/recipe_detail.html
{% extends 'Base.html' %}
{% block title %}
Detail 
{% endblock title %}
{% block content %}
<h1> Detail for {{recipe.title}}</h1>
<h3> likes : {{recipe.like_count}} </h3>
<h4> Time to coock : {{recipe.time_to_cook}}</h4>
<h4> Category: {{recipe.category}} </h4>
<p> Cretaed at <b>{{recipe.created_time}}</b></p>
{% if recipe.image %}
    <img src="{{recipe.image.url}}" alt="{{recipe.title}}" width="200" height="150">
{% endif %}
<br>
<h3> description </h3>
<p>{{recipe.description}}</p>
<br>
<h3> instructions </h3>
<p>{{recipe.instructions}} </p>
<h3> Like </h3>
<form method="post" action="{% url 'review:like' recipe.pk %}">
    {% csrf_token %}    
    {{like_form.as_p}}
    <input type="submit" value="like" />
</form>
<h3> Favorite </h3>
<form method="post" action="{% url 'review:favorite' recipe.pk %}">
    {% csrf_token %}    
    {{like_form.as_p}}
    <input type="submit" value="favorite" />
</form>


<h3> comments </h3>
{% for comm in comments %}
<li><b>{{comm.user}}</b>:{{comm.content}}</li>
{% endfor %}
<h4> Add Comment </h4>

<form method="post" action="{% url 'review:comment' recipe.pk %}">
    {% csrf_token %}    
    {{comment_form.as_p}}
    <input type="submit" value="add comment" />
</form>
<br>



{% if request.user == recipe.user %}
<h3> recipe management </h3>
    <form method="get" action="{% url 'recipe:delete' recipe.pk %}">
        {% csrf_token %}
        <input type="submit" value="delete" />
    </form>
    <br></br>
    <form method="get" action="{% url 'recipe:update' recipe.pk %}">
        {% csrf_token %}
        <input type="submit" value="update" />
    </form>

{% endif %}




{% endblock content %}

templates/recipes/recipe_list.html
{% extends 'Base.html' %}
{% block title %}Recipe List{% endblock title %}

{% block content %}

<h1> Recipe List</h1>
<form >
    {% csrf_token %}
    {{filter.form.as_p}}
    <input type="submit" value="Search" />
</form> 
<br>
<ul>
    {% for recipe in recipes %}
        <li>{{recipe.title}} by user {{recipe.user}} likes: {{recipe.like_count}} </li>
        {% if recipe.image %}
        <img src="{{recipe.image.url}}" alt="{{recipe.title}}" width="200" height="150">
        {% endif %}
    {% endfor %}
</ul>

{% endblock content %}

templates/recipes/recipe_update.html
{% extends 'Base.html' %}
{% block title %}
Recipe Update
{% endblock title %}

{% block content %}
{{recipe}}
<form method="post" >
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Update" >
</form>



{% endblock content %}